### ISSUE TITLE
插件有时不生效

### ISSUE THREAD

**Issue by brightzoe** [azl397985856/leetcode-cheat#2]
- BUG:
进到一个写了题解的题目详情页的时候，插件不生效。例如力扣中国[第4题](https://leetcode-cn.com/problems/median-of-two-sorted-arrays/)，[第15题](https://leetcode-cn.com/problems/3sum/)。
  > 应该是题目名字写错了，url的最后有一两位错了，需要检查一下。

- SUGGESTION：
  - 关于关键点标签，有些比较长，不适合用这种标签式的css叭，不如用要点1，要点2，列表的样式呢呢*φ(゜▽゜*)♪
  - 关于题解标签，是否可以直接显示在插件? 而不是跳转到github或gitee.

**Comment by brightzoe** [comment]
PS：这个pornhub风格的图标，奇奇v怪怪♂♀

**Comment by azl397985856** [comment]
1. 第四题，是因为题目地址错了，少了一个 `s`。
2. 第五题，是因为题目地址错了，多了一个 `- `。
3. 关键点，这个建议不错。
4. 这个就怕太长啊。。。

**Comment by azl397985856** [comment]
close at https://github.com/azl397985856/leetcode-cheat/commit/eb739d7389e12bec41e386369d8a63cc8716ba78
