### ISSUE TITLE
不能复制435题内置用例

### ISSUE THREAD

**Issue by LowryTang** [azl397985856/leetcode-cheat#5]
https://leetcode-cn.com/problems/non-overlapping-intervals/

**Comment by azl397985856** [comment]
我是可以的哦

![image](https://user-images.githubusercontent.com/12479470/103405123-03248c00-4b91-11eb-952b-ede01f70f294.png)

**Comment by azl397985856** [comment]
是你的版本太低了吧？ 你用的是离线么？

**Comment by LowryTang** [comment]
我用的是英文的题目, 所以不能复制, 切换成中文就可以了
![image](https://user-images.githubusercontent.com/4629253/103487537-174bd180-4dbb-11eb-8d23-e1aafb5a1897.png)
![Uploading image.png…]()

**Comment by azl397985856** [comment]
@LowryTang 收到

**Comment by azl397985856** [comment]
已修复，预计下个版本发布就可以了。
