### ISSUE TITLE
BUG: 有效的括号，复制所有内置用例出现问题

### ISSUE THREAD

**Issue by FontEndArt** [azl397985856/leetcode-cheat#7]
[20.有效的括号](https://leetcode-cn.com/problems/valid-parentheses/)
复制所有内置用例出现问题
复制结果如下：
```
 "()"
 "()[]

 "(]"
 "([)]

 "{[]
```

**Comment by FontEndArt** [comment]
394字符串解码也是同样问题，每个用例的后面的双引号变成了换行符

版本：0.8.14

**Comment by azl397985856** [comment]
0.8.15 修复了此问题。（已提交审核，预计几个小时之内可完成，大家可以点击插件的检测更新查询是否有更新）
